### ISSUE TITLE
Unable to run project on macOS Catalina

### ISSUE THREAD

**Issue by degerlac** [SimitTomar/webdriverio-cucumber-pom-boilerplate#1]
After cloning and running npm install, the following is output:
Using node 10.20.1
```
[0-0] RUNNING in chrome - /tests/features/featureFiles/sampleWebdriverioSearch.feature
[0-0]  Error:  Cannot find module 'tang-js-ui-lib'
[0-0] FAILED in chrome - /tests/features/featureFiles/sampleWebdriverioSearch.feature
err { Error: ENOENT: no such file or directory, open 'tests/reports/json/tmp/report.json'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at Object.onComplete (/Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/wdio.conf.js:314:16)
    at Promise.all.onCompleteHook.map (/Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/node_modules/@wdio/cli/build/utils.js:82:13)
    at Array.map (<anonymous>)
    at runOnCompleteHook (/Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/node_modules/@wdio/cli/build/utils.js:80:37)
    at Launcher.run (/Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/node_modules/@wdio/cli/build/launcher.js:83:69)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'tests/reports/json/tmp/report.json' }

S
```

Using node 12.16.3

```[0-0] RUNNING in chrome - /tests/features/featureFiles/sampleWebdriverioSearch.feature
[0-0]  Error:  Cannot find module 'tang-js-ui-lib'
Require stack:
- /Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/tests/pages/sampleHome.page.js
- /Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/tests/features/step_definitions/sampleSearchFunctionality.steps.js
- /Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/node_modules/@wdio/cucumber-framework/build/index.js
- /Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/node_modules/@wdio/utils/build/utils.js
- /Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/node_modules/@wdio/utils/build/initialisePlugin.js
- /Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/node_modules/@wdio/utils/build/index.js
- /Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/node_modules/@wdio/runner/build/index.js
- /Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/node_modules/@wdio/local-runner/build/run.js
[0-0] FAILED in chrome - /tests/features/featureFiles/sampleWebdriverioSearch.feature
err Error: ENOENT: no such file or directory, open 'tests/reports/json/tmp/report.json'
    at Object.openSync (fs.js:458:3)
    at Object.writeFileSync (fs.js:1279:35)
    at Object.onComplete (/Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/wdio.conf.js:314:16)
    at /Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/node_modules/@wdio/cli/build/utils.js:82:13
    at Array.map (<anonymous>)
    at runOnCompleteHook (/Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/node_modules/@wdio/cli/build/utils.js:80:37)
    at Launcher.run (/Users/dgerlach/Documents/projects/wdio6/webdriverio-cucumber-pom-boilerplate/node_modules/@wdio/cli/build/launcher.js:83:69)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'tests/reports/json/tmp/report.json'
}
```

**Comment by SimitTomar** [comment]
There was a reference of tang-js-ui-lib in sampleHome.page.js, removed that and also added the logic to add the top report folder in the onPrepare hook, please try now.

**Comment by SimitTomar** [comment]
Pull the latest master to get the changes!
